### PR TITLE
Request for code review

### PR DESCRIPTION
**Pull request by patriciachrysy**
Dear TSE(s),
Finished struggling with bootstrap :-)
Styled in normal size and responsive size ( all sizes )
Mostly used bootstrap classes, introduced custom CSS classes only when forced to.
I will be waiting for your kind reviews :-)

### CODE REVIEW

**Comment by kobiyoyo** [comment]
## Pull Request under review, by Adama Chubiyojo Desmond (TSE)

**Review by kobiyoyo — CHANGES_REQUESTED** [review]
## Hi @patriciachrysy      
#### Great Job so far, but there are a few more things required. 
### General
- [ ] it's scrolling sideways, let's fix that.

### Tablet Screen
- [ ] The Opinion section should be extended to the right not only left .
### Your Version


### Original Version


### Make changes and submit another code review request.
*Happy coding*

**Comment by patriciachrysy** [comment]
Dear TSE @kobiyoyo,
I tested the page on a smaller computer(14 inches) and I still can't see the double scrollbar you are talking about
If the text on the opinion section is not reaching to the end, it's because it is not long enough. I hope you noticed that it is not the same text as on the one screenshot (it changes almost all the time)
Please take a look again and you may validate if there is no further remark.
Thanks for taking the time to review my project :-)

**Review by pelzolga123 — APPROVED** [review]
Approved.

**Comment by pelzolga123** [comment]
## Hi  Patricia,
## Project looks amazing. Congratulation :+1: Approved.
####  [OPTIONAL] 
#### It's better to avoid using the `!important` flag in future, because it is considered as bad practice.

Go ahead and merge to master.
_Goodluck in your next project_ *Happy coding*

**Pull request merged**
